apiVersion: v1
kind: Service
metadata:
  name: ecommercea3
  labels:
    app: ecommercea3
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: ecommercea3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommercea3
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ecommercea3-ip
  labels:
    app: ecommercea3
spec:
  defaultBackend:
    service:
      name: ecommercea3-backend
      port:
        number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ecommercea3-backend
  labels:
    app: ecommercea3
spec:
  type: NodePort
  selector:
    app: ecommercea3
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommercea3
spec:
  selector:
    matchLabels:
      app: ecommercea3
  template:
    metadata:
      labels:
        app: ecommercea3
    spec:
      containers:
      - name: ecommercea3
        image: gcr.io/ferrous-cogency-304507/ecommercea3:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
